personality = "pragmatic"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"

[projects."/home/kevin/coding/quit-weed"]
trust_level = "trusted"

[projects."/home/kevin/linux-config"]
trust_level = "trusted"

[projects."/home/kevin/coding/portfolio-site"]
trust_level = "trusted"

[projects."/home/kevin/.timetrace"]
trust_level = "trusted"

[projects."/home/kevin/coding/kanban-calendar"]
trust_level = "trusted"

[projects."/home/kevin/coding/nomar-stocks"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/Pictures/screenshots/desktop/resized"]
trust_level = "trusted"

[projects."/home/kevin/coding/red-hat-contributions"]
trust_level = "trusted"

[projects."/home/kevin/coding/me-sniper"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/github-repos/astronofty"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/github-repos/spotify-lib-vis"]
trust_level = "trusted"

[projects."/home/kevin/coding/stb-mkt"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/github-repos/gobcog"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/github-repos/rarity-surf"]
trust_level = "trusted"

[projects."/home/kevin/school/job-hunt"]
trust_level = "trusted"

[projects."/home/kevin/coding/Kevin-Mok"]
trust_level = "trusted"

[projects."/home/kevin/coding/me-sniper/backend"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/github-repos/ME-sniper-backend"]
trust_level = "trusted"

[projects."/home/kevin/Documents/linkedin"]
trust_level = "trusted"

[projects."/home/kevin/coding/zoo-blog"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/hevin/2.28.26 - Toronto Zoo"]
trust_level = "trusted"

[projects."/mnt/ipad/DCIM/100APPLE"]
trust_level = "trusted"

[projects."/mnt/linux-files-3/hevin/2.15.26-zoo"]
trust_level = "trusted"

[projects."/home/kevin/Documents/emails"]
trust_level = "trusted"

[projects."/home/kevin/Documents/chess"]
trust_level = "trusted"

[projects."/home/kevin/coding/spotify-library-intelligence-dashboard"]
trust_level = "trusted"

[projects."/home/kevin/coding/upwork"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.memora]
  command = "memora-server"  # or full path: /path/to/bin/memora-server
  args = ["--no-graph"]

[tui]
notifications = true
notification_method = "osc9"
status_line = ["model-with-reasoning", "five-hour-limit", "context-remaining", "used-tokens", "current-dir"]
