#!/bin/bash

. "/home/kevin/.cache/wal/colors.sh"

# Read from k10temp's Tctl sensor for AMD CPU temperature
temp="$(sensors | rg 'Tctl:' | awk '{ print $2 }' | rg -o '\d{2}' | sed 's/$/°C/')"
printf "%s\n\n%s\n" "$temp" "$color7"
