#!/bin/bash

picom &
imwheel
xmodmap ~/.Xmodmap

redshift -O 3000
xset r rate $XSET_DELAY $XSET_RATE
/usr/lib/notification-daemon-1.0/notification-daemon &
picom &
imwheel &
numlockx on &

#start-pulseaudio-x11 &
#sudo alsa force-reload
#pulseaudio --start

wal -i $(/home/kevin/scripts/shuffler "$HOME/Pictures/Backgrounds/dim/editing") &
